version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8899:8899
    env_file:
      - ./.env
    volumes:
      - ./app:/usr/src/app/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8899 --reload
  
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: passw0rd
      POSTGRES_DB: fastapi
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:

